--- 
networks: 
  firefly_iii_net: 
    driver: bridge
  web:
    external: true
services: 
  firefly_iii_app: 
    image: jc5x/firefly-iii:latest
    depends_on:
      - firefly_iii_db
    networks: 
#      - firefly_iii_net
      - web
    ports: 
      - "4040:80"
    env_file: .env
    volumes: 
      - 
        source: firefly_iii_export
        target: /var/www/firefly-iii/storage/export
        type: volume
      - 
        source: firefly_iii_upload
        target: /var/www/firefly-iii/storage/upload
        type: volume
    labels:
      - traefik.frontend.rule=Host:${FIREFLY_URL}
      - traefik.backend=firefly_firefly_iii_app_1
      - traefik.docker.network=web
      - traefik.port=80
  firefly_iii_db: 
    image: "postgres:10"
    environment:
      - POSTGRES_PASSWORD=${FIREFLY_PASS}
      - POSTGRES_USER=firefly
    networks: 
#      - firefly_iii_net
       - web
    volumes: 
      - firefly_iii_db:/var/lib/postgresql/data
version: "3.2"
volumes: 
  firefly_iii_db: ~
  firefly_iii_export: ~
  firefly_iii_upload: ~
