version: "3.3"

services:

  traefik:
    image: "traefik:1.7.6-alpine"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - $HOME/traefik.toml:/traefik.toml
      - $HOME/acme.json:/acme.json
    labels:
      - "traefik.frontend.rule=Host:${TRAEFIK_URL}"
      - "traefik.port=8080"
networks:
  default:
    external:
      name: web
